### ISSUE TITLE
【教程】使用Github Markdown 放长文

### ISSUE THREAD

**Issue by ThisIsPhoton** [ThisIsPhoton/tortuleForLof#7]
### 1. 首先点进你的github主页，进入创建好的仓库
找不到主页的点左上角的猫猫头logo就会进入这个主页页面啦
然后看到左边这栏，Repositories，就是你刚刚建好的仓库。
点进去（我这里建了个名为test的测试仓库）
![image](https://user-images.githubusercontent.com/58095532/83360839-4b0cd780-a352-11ea-8c03-75f42481aa6f.png)

### 2. 进入仓库后，新建文本文件
一个没有文件的仓库，点进去后长这样
点击图中create a new file创建文本文件
![image](https://user-images.githubusercontent.com/58095532/83360916-e69e4800-a352-11ea-88e9-cce47a4b8de2.png)

### 3. 为新建的文本文件命名，填入内容
文件名随意，但后缀一定要是【.md】
中间的编辑框就是贴正文的地方
![image](https://user-images.githubusercontent.com/58095532/83361027-91af0180-a353-11ea-982f-90121a996db7.png)
* 注意： 因为markdown排版规则，粘贴正文之后，两个段落之间空一行，提交后才会显示分段。

文件名和正文搞好后往下拉，点击Commit提交文件
![image](https://user-images.githubusercontent.com/58095532/83361069-cfac2580-a353-11ea-9aa2-f133e5ee331d.png)

### 4. 提交后会回到Code界面，再点进刚刚创建的文件
![image](https://user-images.githubusercontent.com/58095532/83361117-46e1b980-a354-11ea-8d43-7becfaeed95c.png)
点进去之后就是文本文件的预览了，【该页面的链接复制粘贴发给亲友~】
右上角这两个小图标是重新编辑和删除。
![image](https://user-images.githubusercontent.com/58095532/83361149-8d371880-a354-11ea-9fb4-b4834ad88698.png)

### 5. 同一个仓库中创建更多文本文件，点这里
![image](https://user-images.githubusercontent.com/58095532/83361200-f159dc80-a354-11ea-9854-0408a1934d6a.png)

**Comment by ThisIsPhoton** [comment]
### 【小技巧】如何给markdown文本排版

### 0. 如果提交之后，文章该分段的没分段
因为markdown排版规则，粘贴正文之后，两个段落之间【需要空一行】，提交后才会显示分段。

### 1. 首先是最简单的增加章节标题。在标题文字前加井号就可以了。
编辑界面长这样：
![image](https://user-images.githubusercontent.com/58095532/83361399-ae990400-a356-11ea-93f7-ad964bdbe75e.png)

提交之后浏览页面长这样：
![image](https://user-images.githubusercontent.com/58095532/83361404-b9539900-a356-11ea-9888-52cbd82e30c4.png)

一般用一号标题或者二号标题作为文章标题，三号/四号作为段落标题
当然只要自己看着舒服就行
顺便一提，Issue里也可以用这个方式添加标题


### 2. 什么你们还想看其他小技巧
只用来发文其他排版格式好像没啥用emmm
但是markdown其实有很多东西，比如加粗、斜线、高亮、添加表格，图片.....
这里先丢个其他人写的教程链接好了：[github_markdown语法大全整理](https://www.jianshu.com/p/40ba812dd973)
使用【Ctrl+F】搜索想学习东西的关键词

===========
最后，有不懂的欢迎评论区问我！
还有什么别的想看的也可以评论~~

**Comment by CrazyLain** [comment]
就是如果用md文件，每次修改记录是能被搜索到的。
